ignore:
    - .git
    - bin
    - rice-box.go

build:
    - gofmt -w -s -e .
    - rice embed-go
    - go vet ./...
    - go test ./...
    - go build -race -o bin/SoundBert-race .
    - go build -o bin/SoundBert .
