language: go

go:
    - 1.6

install:
    - go get github.com/GeertJohan/go.rice/rice
    - go get github.com/golang/lint/golint
    - go get github.com/HorayNarea/SoundBert

script:
    - gofmt -d -l -s -e .
    - golint
    - rice embed-go
    - go vet ./...
    - go test ./...
    - go build -o bin/SoundBert .
